
// This file has been generated by the GUI designer. Do not modify.
public partial class MainWindow
{
	private global::Gtk.VBox vbox1;
	private global::Gtk.GLWidget glwidget2;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		this.BorderWidth = ((uint)(15));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox ();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.glwidget2 = new global::Gtk.GLWidget ();
		this.glwidget2.Name = "glwidget2";
		this.glwidget2.SingleBuffer = false;
		this.glwidget2.ColorBPP = 0;
		this.glwidget2.AccumulatorBPP = 0;
		this.glwidget2.DepthBPP = 0;
		this.glwidget2.StencilBPP = 0;
		this.glwidget2.Samples = 0;
		this.glwidget2.Stereo = false;
		this.glwidget2.GlVersionMajor = 0;
		this.glwidget2.GlVersionMinor = 0;
		this.vbox1.Add (this.glwidget2);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.glwidget2]));
		w1.Position = 0;
		w1.Expand = false;
		w1.Fill = false;
		this.Add (this.vbox1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 922;
		this.DefaultHeight = 541;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
	}
}
